name=UI
version=1.0.0
author=Pico2Seq-dev
maintainer=Pico2Seq-dev
sentence=A library for handling user interface components.
paragraph=Manages button presses, UI state, and event handling for the sequencer.
category=Signal Input/Output
url=
architectures=*
includes=UI.h
