name=Voice
version=1.0.0
author=Pico2Seq-dev
maintainer=Pico2Seq-dev
sentence=A library for voice management and synthesis.
paragraph=Provides a flexible voice architecture for creating and managing multiple synthesizer voices, including oscillators, filters, and effects.
category=Signal Input/Output
url=
architectures=*
includes=Voice.h
