name=LEDMatrix
version=1.0.0
author=Pico2Seq-dev
maintainer=Pico2Seq-dev
sentence=A library for controlling an 8x8 LED matrix.
paragraph=Provides an interface for controlling an 8x8 WS2812B LED matrix, including setting individual LEDs, and handling animations and feedback.
category=Display
url=
architectures=*
includes=LEDMatrix.h
