#pragma once

#include "IHardwareModule.h"
#include "HardwareRegistry.h"
#include <functional>
#include <array>
#include <vector>
#include <cstdint>

// Forward declarations
struct MatrixButtonEvent;
class UIState;
class Sequencer;
class MidiNoteManager;

/**
 * Fallback Configuration Structures
 * Define how each module's fallback controls are configured
 */

/**
 * Touch Matrix Fallback Configuration
 * Uses 4 digital buttons to replace MPR121 touch matrix
 */
struct TouchMatrixFallbackConfig {
    uint8_t buttonPins[4] = {2, 3, 4, 5};  // GPIO pins for 4 buttons
    bool useInternalPullups = true;         // Enable internal pull-up resistors
    uint32_t debounceTimeMs = 50;          // Button debounce time
    bool isActive = false;                  // Current activation state
};

/**
 * Distance Sensor Fallback Configuration  
 * Uses step button + AS5600 encoder for parameter modification
 */
struct DistanceSensorFallbackConfig {
    uint8_t stepButtonPin = 8;             // Pin for step selection
    bool requiresAS5600 = true;            // Requires magnetic encoder for value adjustment
    float sensitivity = 1.0f;              // Adjustment sensitivity multiplier
    bool isActive = false;                 // Current activation state
    uint8_t currentStepButton = 0;         // Currently held step button (0 = none)
};

/**
 * Magnetic Encoder Fallback Configuration
 * Uses increment/decrement buttons to replace AS5600 encoder
 */
struct MagneticEncoderFallbackConfig {
    uint8_t incrementPin = 6;              // GPIO pin for increment button
    uint8_t decrementPin = 7;              // GPIO pin for decrement button
    bool useInternalPullups = true;        // Enable internal pull-up resistors
    uint32_t debounceTimeMs = 50;          // Button debounce time
    uint32_t repeatDelayMs = 500;          // Initial repeat delay
    uint32_t repeatRateMs = 100;           // Repeat rate for held buttons
    bool isActive = false;                 // Current activation state
};

/**
 * Fallback Event Types
 * Define the types of events that can be generated by fallback controls
 */
enum class FallbackEventType : uint8_t {
    TOUCH_MATRIX_PRESS,      // Simulated touch matrix button press
    TOUCH_MATRIX_RELEASE,    // Simulated touch matrix button release
    DISTANCE_VALUE_CHANGE,   // Simulated distance sensor value change
    ENCODER_INCREMENT,       // Simulated encoder increment
    ENCODER_DECREMENT,       // Simulated encoder decrement
    STEP_BUTTON_PRESS,       // Step button press for distance fallback
    STEP_BUTTON_RELEASE      // Step button release for distance fallback
};

/**
 * Fallback Event Structure
 * Contains event data for fallback control events
 */
struct FallbackEvent {
    FallbackEventType type;
    ModuleType sourceModule;
    uint8_t buttonIndex;     // For touch matrix and step buttons
    float value;             // For distance and encoder values
    uint32_t timestamp;      // Event timestamp
};

/**
 * Fallback Control Manager Class
 * 
 * Manages alternative control methods when hardware modules are missing.
 * Handles activation/deactivation of fallback controls and routes input events
 * between hardware and fallback mechanisms for seamless operation.
 * 
 * Requirements: 2.1, 2.2, 2.3, 2.4
 */
class FallbackControlManager {
private:
    // Configuration storage for each fallback type
    TouchMatrixFallbackConfig touchMatrixConfig;
    DistanceSensorFallbackConfig distanceSensorConfig;
    MagneticEncoderFallbackConfig magneticEncoderConfig;
    
    // Button state tracking for fallback controls
    struct ButtonState {
        bool isPressed = false;
        uint32_t pressTime = 0;
        uint32_t lastRepeatTime = 0;
        bool isRepeating = false;
    };
    
    std::array<ButtonState, 4> touchMatrixButtonStates;  // 4 fallback buttons
    ButtonState stepButtonState;                         // Step button for distance fallback
    ButtonState incrementButtonState;                    // Increment button for encoder fallback
    ButtonState decrementButtonState;                    // Decrement button for encoder fallback
    
    // Event callback for routing fallback events
    std::function<void(const FallbackEvent&)> eventCallback;
    
    // Reference to hardware registry for status queries
    HardwareRegistry* hardwareRegistry;
    
    // Internal state
    bool isInitialized = false;
    uint32_t lastUpdateTime = 0;
    
public:
    FallbackControlManager() = default;
    ~FallbackControlManager() = default;
    
    // Disable copy/move to prevent accidental duplication
    FallbackControlManager(const FallbackControlManager&) = delete;
    FallbackControlManager& operator=(const FallbackControlManager&) = delete;
    FallbackControlManager(FallbackControlManager&&) = delete;
    FallbackControlManager& operator=(FallbackControlManager&&) = delete;
    
    // Initialization and configuration
    
    /**
     * Initialize the fallback control manager
     * @param registry Reference to hardware registry for status queries
     * @param callback Function to call when fallback events are generated
     * @return true if initialization successful
     */
    bool initialize(HardwareRegistry& registry, 
                   std::function<void(const FallbackEvent&)> callback);
    
    /**
     * Configure touch matrix fallback settings
     * @param config Touch matrix fallback configuration
     */
    void configureTouchMatrixFallback(const TouchMatrixFallbackConfig& config);
    
    /**
     * Configure distance sensor fallback settings
     * @param config Distance sensor fallback configuration
     */
    void configureDistanceSensorFallback(const DistanceSensorFallbackConfig& config);
    
    /**
     * Configure magnetic encoder fallback settings
     * @param config Magnetic encoder fallback configuration
     */
    void configureMagneticEncoderFallback(const MagneticEncoderFallbackConfig& config);
    
    // Fallback activation/deactivation methods
    
    /**
     * Activate fallback controls for a specific module
     * @param moduleType Module to activate fallback for
     * @return true if fallback was successfully activated
     */
    bool activateFallback(ModuleType moduleType);
    
    /**
     * Deactivate fallback controls for a specific module
     * @param moduleType Module to deactivate fallback for
     * @return true if fallback was successfully deactivated
     */
    bool deactivateFallback(ModuleType moduleType);
    
    /**
     * Check if fallback is active for a specific module
     * @param moduleType Module to check
     * @return true if fallback is currently active
     */
    bool isFallbackActive(ModuleType moduleType) const;
    
    /**
     * Activate all available fallback controls
     * Called when multiple modules are missing
     */
    void activateAllFallbacks();
    
    /**
     * Deactivate all fallback controls
     * Called when hardware modules are restored
     */
    void deactivateAllFallbacks();
    
    // Input event routing methods
    
    /**
     * Process hardware input events and route through fallback if needed
     * @param evt Matrix button event from hardware or fallback
     * @param uiState UI state for event processing
     * @param sequencers Array of sequencer pointers
     * @param sequencerCount Number of sequencers
     * @param midiNoteManager MIDI note manager for output
     */
    void routeMatrixEvent(const MatrixButtonEvent& evt,
                         UIState& uiState,
                         Sequencer* const* sequencers,
                         size_t sequencerCount,
                         MidiNoteManager& midiNoteManager);
    
    /**
     * Process distance sensor input and route through fallback if needed
     * @param distance Distance value from sensor or fallback
     * @param uiState UI state for parameter updates
     * @param sequencers Array of sequencer pointers
     * @param sequencerCount Number of sequencers
     */
    void routeDistanceInput(float distance,
                           UIState& uiState,
                           Sequencer* const* sequencers,
                           size_t sequencerCount);
    
    /**
     * Process encoder input and route through fallback if needed
     * @param encoderValue Encoder value from hardware or fallback
     * @param uiState UI state for parameter updates
     * @param sequencers Array of sequencer pointers
     * @param sequencerCount Number of sequencers
     */
    void routeEncoderInput(int16_t encoderValue,
                          UIState& uiState,
                          Sequencer* const* sequencers,
                          size_t sequencerCount);
    
    // Runtime update methods
    
    /**
     * Update fallback control states (call from main loop)
     * Handles button debouncing, repeat logic, and event generation
     */
    void update();
    
    /**
     * Handle fallback event generated internally
     * @param event Fallback event to process
     */
    void handleFallbackEvent(const FallbackEvent& event);
    
    // Status and configuration query methods
    
    /**
     * Get current touch matrix fallback configuration
     * @return const reference to touch matrix config
     */
    const TouchMatrixFallbackConfig& getTouchMatrixConfig() const { return touchMatrixConfig; }
    
    /**
     * Get current distance sensor fallback configuration
     * @return const reference to distance sensor config
     */
    const DistanceSensorFallbackConfig& getDistanceSensorConfig() const { return distanceSensorConfig; }
    
    /**
     * Get current magnetic encoder fallback configuration
     * @return const reference to magnetic encoder config
     */
    const MagneticEncoderFallbackConfig& getMagneticEncoderConfig() const { return magneticEncoderConfig; }
    
    /**
     * Check if any fallback controls are currently active
     * @return true if at least one fallback is active
     */
    bool hasActiveFallbacks() const;
    
    /**
     * Get list of modules currently using fallback controls
     * @return vector of module types in fallback mode
     */
    std::vector<ModuleType> getActiveFallbackModules() const;
    
private:
    // Internal helper methods
    
    /**
     * Initialize GPIO pins for touch matrix fallback
     */
    void initializeTouchMatrixPins();
    
    /**
     * Initialize GPIO pins for distance sensor fallback
     */
    void initializeDistanceSensorPins();
    
    /**
     * Initialize GPIO pins for magnetic encoder fallback
     */
    void initializeMagneticEncoderPins();
    
    /**
     * Update touch matrix fallback button states
     */
    void updateTouchMatrixFallback();
    
    /**
     * Update distance sensor fallback button states
     */
    void updateDistanceSensorFallback();
    
    /**
     * Update magnetic encoder fallback button states
     */
    void updateMagneticEncoderFallback();
    
    /**
     * Generate fallback event and call callback
     * @param event Event to generate
     */
    void generateFallbackEvent(const FallbackEvent& event);
    
    /**
     * Map fallback button index to touch matrix button index
     * @param fallbackButton Fallback button index (0-3)
     * @return Touch matrix button index
     */
    uint8_t mapFallbackToTouchMatrix(uint8_t fallbackButton) const;
    
    /**
     * Check if button state has changed and handle debouncing
     * @param pin GPIO pin to read
     * @param buttonState Button state structure to update
     * @return true if button state changed after debouncing
     */
    bool updateButtonState(uint8_t pin, ButtonState& buttonState);
    
    /**
     * Handle button repeat logic for held buttons
     * @param buttonState Button state to check for repeat
     * @return true if repeat event should be generated
     */
    bool handleButtonRepeat(ButtonState& buttonState);
};